#!/usr/bin/env bash
#Configure web-02 to be identical to web-01.
#Add a custom Nginx response header to be able to rack which webswerver is answering the HTTPs requests.shouldd containd a custom header(on web-01 and web-02)
#the name of the custom HTTP header must be X-Served-By
#the value of the custom HTTP header must be a host name of the server Nginx is running on
#ignore SC2154

# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
