#!/usr/bin/env bash
# Bash script that configures a server to the above requirements
# configures nginx to run and listen to port 80
# to install whatever tool you need, start and destroy as many containers
# as you need to debug the issue. Then, write a Bash script with the

mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
