#!/usr/bin/env bash
# Script configures for localhost resolve to 127.0.0.2 and facebook.com resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
